name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test
